/*
 * This file is generated by jOOQ.
 */
package domain.jooq;


import domain.jooq.tables.Chats;
import domain.jooq.tables.Links;
import domain.jooq.tables.records.ChatsRecord;
import domain.jooq.tables.records.LinksRecord;

import javax.annotation.processing.Generated;

import org.jooq.ForeignKey;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;


/**
 * A class modelling foreign key relationships and constraints of tables in the
 * default schema.
 */
@Generated(
    value = {
        "https://www.jooq.org",
        "jOOQ version:3.17.6"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Keys {

    // -------------------------------------------------------------------------
    // UNIQUE and PRIMARY KEY definitions
    // -------------------------------------------------------------------------

    public static final UniqueKey<ChatsRecord> CONSTRAINT_3 = Internal.createUniqueKey(Chats.CHATS, DSL.name("CONSTRAINT_3"), new TableField[] { Chats.CHATS.ID }, true);
    public static final UniqueKey<ChatsRecord> CONSTRAINT_3D = Internal.createUniqueKey(Chats.CHATS, DSL.name("CONSTRAINT_3D"), new TableField[] { Chats.CHATS.CHAT_ID }, true);
    public static final UniqueKey<LinksRecord> CONSTRAINT_4 = Internal.createUniqueKey(Links.LINKS, DSL.name("CONSTRAINT_4"), new TableField[] { Links.LINKS.ID }, true);

    // -------------------------------------------------------------------------
    // FOREIGN KEY definitions
    // -------------------------------------------------------------------------

    public static final ForeignKey<LinksRecord, ChatsRecord> CONSTRAINT_45 = Internal.createForeignKey(Links.LINKS, DSL.name("CONSTRAINT_45"), new TableField[] { Links.LINKS.CHAT_ID }, Keys.CONSTRAINT_3D, new TableField[] { Chats.CHATS.CHAT_ID }, true);
}
