/*
 * This file is generated by jOOQ.
 */
package domain.jooq.tables.pojos;


import jakarta.validation.constraints.Size;

import java.beans.ConstructorProperties;
import java.io.Serializable;

import javax.annotation.processing.Generated;

import org.jetbrains.annotations.NotNull;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "https://www.jooq.org",
        "jOOQ version:3.17.6"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Links implements Serializable {

    private static final long serialVersionUID = 1L;

    private Long id;
    private Long chatId;
    private String linkUrl;

    public Links() {}

    public Links(Links value) {
        this.id = value.id;
        this.chatId = value.chatId;
        this.linkUrl = value.linkUrl;
    }

    @ConstructorProperties({ "id", "chatId", "linkUrl" })
    public Links(
        @NotNull Long id,
        @NotNull Long chatId,
        @NotNull String linkUrl
    ) {
        this.id = id;
        this.chatId = chatId;
        this.linkUrl = linkUrl;
    }

    /**
     * Getter for <code>LINKS.ID</code>.
     */
    @jakarta.validation.constraints.NotNull
    @NotNull
    public Long getId() {
        return this.id;
    }

    /**
     * Setter for <code>LINKS.ID</code>.
     */
    public void setId(@NotNull Long id) {
        this.id = id;
    }

    /**
     * Getter for <code>LINKS.CHAT_ID</code>.
     */
    @jakarta.validation.constraints.NotNull
    @NotNull
    public Long getChatId() {
        return this.chatId;
    }

    /**
     * Setter for <code>LINKS.CHAT_ID</code>.
     */
    public void setChatId(@NotNull Long chatId) {
        this.chatId = chatId;
    }

    /**
     * Getter for <code>LINKS.LINK_URL</code>.
     */
    @jakarta.validation.constraints.NotNull
    @Size(max = 255)
    @NotNull
    public String getLinkUrl() {
        return this.linkUrl;
    }

    /**
     * Setter for <code>LINKS.LINK_URL</code>.
     */
    public void setLinkUrl(@NotNull String linkUrl) {
        this.linkUrl = linkUrl;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final Links other = (Links) obj;
        if (this.id == null) {
            if (other.id != null)
                return false;
        }
        else if (!this.id.equals(other.id))
            return false;
        if (this.chatId == null) {
            if (other.chatId != null)
                return false;
        }
        else if (!this.chatId.equals(other.chatId))
            return false;
        if (this.linkUrl == null) {
            if (other.linkUrl != null)
                return false;
        }
        else if (!this.linkUrl.equals(other.linkUrl))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.id == null) ? 0 : this.id.hashCode());
        result = prime * result + ((this.chatId == null) ? 0 : this.chatId.hashCode());
        result = prime * result + ((this.linkUrl == null) ? 0 : this.linkUrl.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Links (");

        sb.append(id);
        sb.append(", ").append(chatId);
        sb.append(", ").append(linkUrl);

        sb.append(")");
        return sb.toString();
    }
}
